# Linear Regression

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
x = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(x, np.array([1,2]))+3
reg = LinearRegression().fit(x,y)
reg.score(x,y)

1.0

In [5]:
reg.predict(np.array([[3,5]]))

array([16.])

# Logistic Regression

In [6]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [8]:
x , y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0).fit(x,y)

C:\Users\Nouman Ahmad\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Nouman Ahmad\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [14]:
clf.predict(x[:2,:])

array([0, 0])

In [10]:
clf.score(x,y)

0.96

# K-Nearest Neighbor

In [17]:
x = [[0],[1],[2],[3]]
y = [0,0,1,1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x,y)
neigh.predict([[1.1]])
neigh.predict_proba([[0.9]])

array([[0.66666667, 0.33333333]])

# SVM Classifier

In [18]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [20]:
x = np.array([[-1,-1],[-2,-1],[1,1],[2,1]])
y = np.array([1,1,2,2])
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(x,y)
clf.predict([[-0.8,-1]])

array([1])

# Naive Bayes

In [22]:
x = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
y = np.array([1,1,1,2,2,2])
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x,y)
clf.predict([[-0.8,-1]])

array([1])

# Thanks for watching this please subscribe and link this  